### ISSUE TITLE
can't build libbeato in build-directory: jkweb/common.h: No such file or directory

### ISSUE THREAD

**Issue by mschilli87** [CRG-Barcelona/libbeato#3]
If I run `git clone http://github.com/CRG-Barcelona/libbeato.git && cd libbeato && ./configure && make` it runs just fine.
Also installing to a local directory without `root` permissions as per `git clone http://github.com/CRG-Barcelona/libbeato.git && cd libbeato && mkdir install && ./configure --prefix=$(pwd)/install && make && make install` works without problems.
However, if I attempt to separate between the source (i.e. the cloned `git` repository) & the build files (e.g. to build `libbeato` on several systems based on the same (i.e. shared) copy of the source files, `make` fails: `git clone http://github.com/CRG-Barcelona/libbeato.git && mkdir libbeato.build && cd libbeato.build && ../libbeato/configure && make`

    Cloning into 'libbeato'...

    [...]
    <output truncated>
    [...]
    
    make[2]: Leaving directory `/tmp/test/libbeato.build/jkweb'
    Making all in beato
    make[2]: Entering directory `/tmp/test/libbeato.build/beato'
    gcc -DHAVE_CONFIG_H -I. -I../../libbeato/beato -I..    -Wall -Wformat -Wimplicit -Wreturn-type -Wuninitialized -fno-strict-aliasing -g -O2 -MT bbiAugment.o -MD -MP -MF .deps/bbiAugment.Tpo -c -o bbiAugment.o ../../libbeato/beato/bbiAugment.c
    ../../libbeato/beato/bbiAugment.c:1:26: fatal error: jkweb/common.h: No such file or directory
     #include <jkweb/common.h>
                              ^
    compilation terminated.
    make[2]: *** [bbiAugment.o] Error 1
    make[2]: Leaving directory `/tmp/test/libbeato.build/beato'
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory `/tmp/test/libbeato.build'
    make: *** [all] Error 2

**Comment by andypohl** [comment]
Well I know why the error happens.  I'll fidget with the Makefile.am in libbeato/beato to see if I can make this style of building work.

**Comment by andypohl** [comment]
I've updated it so it should include the top-level source directory.  git pull and try again.

**Comment by mschilli87** [comment]
fixed by d62f4f546856d8ccb463d4215d41d88d6d797380
